[package]
name = "serde-with-extras"
version = "0.1.0-alpha.1"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }

[dependencies]
serde = { workspace = true, features = ["derive"] }
indexmap = { workspace = true, features = ["serde"] }

[dev-dependencies]
serde_json = { workspace = true }
insta = { workspace = true }
