[package]
name = "serde-metadata"
version = "0.1.0-alpha.1"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }

[dependencies]
indexmap = { workspace = true }
serde = { workspace = true }
