[package]
name = "serde-redes"
version = "0.1.0-alpha.1"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }

[dependencies]
